- RCTYouTube.xcodeproj/project.pbxproj
This spike fixes https://github.com/paramaggarwal/react-native-youtube/issues/2. Details documented in the issue.
I don't know if this is the best-practices way of handling such cases, but this change fixed the problem for me. Feel free to accept or reject at will.
> Fix `RCTViewManager.h file not found`

- RCTYouTubeManager.m
- YouTube.ios.js
Fixes issue https://github.com/paramaggarwal/react-native-youtube/issues/6, caused by the event name `onError` colliding with an identically named event published by React Native core `RCTImageViewManager`.
Renamed the other events as well to safeguard from incompatibilities with other libraries, or future changes in React Native.
> Fix native event name collisions

- README.md
After the Android installation instructions were added, the "Activated sound when phone is on vibrate mode" that refers to AppDelegate is listed under the Android area.  I figured it should be up under the iOS section since it is iOS specific.
> fix README.  Move last part of iOS installation back under iOS section

- RCTYouTube/src/main/java/com/inprogress/reactnativeyoutube/YouTubeManager.java
Hi, first of all, awesome library, keep up the good work!
This pull request fixes the 'More than one plugin attempted to publish the same registration name `onError` when using react-native 0.39.
This also fixes the event handlers for Android. The handlers defined `YouTube.android.js` were never triggered because the event names in the .java file were different. By accident the handlers passed to the YouTube component were still called, but directly by the native-code. This caused the arguments to be wrong. This commit fixes that as well.
> Fix for “More than one plugin attempted to publish the same registration name `onError` when using RN 0.39

- RCTYouTube/src/main/java/com/inprogress/reactnativeyoutube/YouTubeManager.java
- RCTYouTube/src/main/java/com/inprogress/reactnativeyoutube/YouTubePlayerController.java
- RCTYouTube/src/main/java/com/inprogress/reactnativeyoutube/YouTubeView.java
- README.md
- YouTube.android.js
- YouTube.ios.js
This pull requests adds support for the `fs` prop. By default the fullscreen button is shown. This prop can be used to disable this button. Works on both Android and iOS.
> Added support for the `fs` prop in order to hide the full-screen button

- RCTYouTube/src/main/java/com/inprogress/reactnativeyoutube/YouTubeManager.java
- RCTYouTube/src/main/java/com/inprogress/reactnativeyoutube/YouTubePlayerController.java
- README.md
- YouTube.android.js
The prop `playsInline` doesn't work on Android. After inspecting I found that it is removed entirely from the props in `YouYube.android.js` (at the bottom). After further investigation I found that inline playback support is working very poorly. This pull requests adds proper inline playback handling for Android. It addresses the following issues:
- fix full-screen mode always started on load when play is false
- cue video when play is false so you can tap it to start the video
- start full-screen mode when video starts playing and inline is not enabled
- exit full-screen mode when video is ended and inline is enabled
- stop video from playing when exiting full-screen and inline is not enabled
- pause video playback when videoId prop is reset
- fix, don't start playback of video when …
> Fixed/added support for inline playback support on Android

- Example/RCTYouTubeExampleTests/RCTYouTubeExampleTests.m
- Example/iOS/AppDelegate.m
- RCTYouTube.m
- RCTYouTubeManager.h
- RCTYouTubeManager.m
- package.json
* fixes inProgress-team/react-native-youtube#88
> Support React Native 0.40.x header imports

- README.md
Change the settings.gradle projectDir to ../node_modules/react-native-youtube/android intead of ../node_modules/react-native-youtube/RCTYouTube.
Fix the "Configuration with name 'default' not found" error.
> Fix android install instruction

- YTPlayerView/YTPlayerView.m
- package.json
Fixed a bug that prevents videos from being auto played in full screen if playsInline is set to false so that video is displayed. See #136
> iOS 10 playsInline false fix

- react-native-youtube.podspec
Hi there,
I added a podspec so this lib can be used on iOS apps that use CocoaPods to manage React Native.
Example usage in Podfile
```
[...]
pod 'react-native-youtube', :path => '../node_modules/react-native-youtube'
```
Let me know what you think.
> Add CocoaPods podspec

- .gitignore
- YouTubeStandalone.android.js
- android/src/main/java/com/inprogress/reactnativeyoutube/YouTubeModule.java
- example/RCTYouTubeExample.js
- main.js
I added the possibility to run a YouTube player as a standalone player. It uses the same native module but it exports as YouTubeStandalone to be used in React . Needless to say, it only works for Android. 
The player can be started just using `YouTubeStandalone.playVideo("apiKey", "videoId", autoplay, lightbox, startTimeMillis)`
It's missing a few extra functionalities from the standalone player, but I will add them later, like using a playlist or a list of videos
Let me now what you guys think
> Add Standalone Player

- android/src/main/java/com/inprogress/reactnativeyoutube/ReactNativeYouTube.java
[`createJSModules` is now not required on Android](https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8) from RN 0.47. I actually can't build an app on RN 0.47 without removing this method/@ovveride marker. This should be backwards compatible.
> Remove createJSModules - RN 0.47 compatibility

- android/src/main/java/com/inprogress/reactnativeyoutube/YouTubeView.java
We cannot commit on fragment manager after the view has been removed. 
Fixes:
```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1434)
at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1452)
at android.app.BackStackRecord.commitInternal(BackStackRecord.java:708)
at android.app.BackStackRecord.commit(BackStackRecord.java:672)
at com.inprogress.reactnativeyoutube.YouTubeView.onAttachedToWindow(YouTubeView.java:39)
at android.view.View.dispatchAttachedToWindow(View.java:15509)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2916)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
at …
```
> Check if savedinstancestate has already occurred.

- react-native-youtube.podspec
If you include react-native-youtube using your Podfile, i.e.:
```
pod 'react-native-youtube', :path => 'node_modules/react-native-youtube'
```
At runtime your project will fail to find the YTPlayerView-iframe-player.html. This is because we now embed YTPlayerView.{h,m}, which contains new logic for how it detects the YTPlayerView-iframe-player.html.
Thus, we need to update our .podspec file to include references both to our newly embedded YTPlayerView.{h,m} and our included YTPlayerView-iframe-player.html.
> Update podspec to reflect the fact that we now embed YTPlayerView

- android/src/main/java/com/inprogress/reactnativeyoutube/YouTubeView.java
There is a crashing bug when closing an activity with a ReactRootView that contains a YouTube component.
Specifically, this line:
https://github.com/inProgress-team/react-native-youtube/blob/master/android/src/main/java/com/inprogress/reactnativeyoutube/YouTubeView.java#L60
` fragmentManager.beginTransaction().remove(mYouTubePlayerFragment).commit();`
Triggers an exception if the activity has already been destroy.
We need to check to see if the activity has not yet been destroyed before using our fragmentManager.
> Fix crashing bug: java.lang.IllegalStateException: Activity has been destroyed 

- README.md
This is a very trivial change to correct a typo while I was following the README.
Reference:
https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubePlayer.PlayerStyle
> Fix CHROMELESS typo in README

- example/package.json
Not really sure, however, since the version of react-native-youtube is 2.0.1, the `npm pack ..` command packs a `react-native-youtube-2.0.1.tgz` file for us. The version in package.json in example should be modified, too.
Otherwise, error be thrown out like this
```
npm ERR! code ENOENT
npm ERR! syscall stat
npm ERR! path /Users/user/Documents/react-native-youtube/example/react-native-youtube-2.0.0.tgz
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, stat '/Users/user/Documents/react-native-youtube/example/react-native-youtube-2.0.0.tgz'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2020-05-09T16_58_41_447Z-debug.log
```
> Change version to 2.0.1 in pacakge.json in example

- main.d.ts
apiKey is missing in types. Its a mandatory prop.
> fix(types): Add missing apiKey type inside YouTubeProps

- YouTube.android.js
- YouTube.ios.js
- package.json
Using `react-native-youtube` v2.0.2 with RN v0.69 leads to the following error:
`ERROR  Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'`
This PR fixes the import statements as suggested.
> Fix ViewPropTypes deprecation error

- android/src/main/java/com/inprogress/reactnativeyoutube/YouTubeStandaloneModule.java
- main.d.ts
- tests/type-test.tsx
I've noticed that when you have more than one app that can launch a standalone player for YouTube, your app will present a dialog for you to choose which app do you wish to use. If you close the dialog without choosing an option, the YoutubeStandaloneModule throws a RuntimeException that is not handled by the lib causing the app to crash.
Therefore I've wrapped the block inside a try catch and rejected the promise if the runtime error occurs.
I also fixed a few type definitions.
> Handling RuntimeException thrown by YouTubeStandalonePlayer.getReturnedInitializationResult
